version: "3.6"
services:
    nginx:
        container_name: nginx
        image: nginx
        restart: "no"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./:/www/
        ports:
            - 81:80
